/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM32F103C6_GPIO_DRIVER.h"
#include "stm32f103C6_exit_driver.h"
#include "stm32f103x6.h"
#include "lcd.h"
#include "kepad.h"




unsigned char EXTI_flag ;
 EXTI_PinConfig_t PINCONFIG;
void mywait(unsigned int time)
{
	int i, j;

	for(i = 0 ; i < 255 ; i++){

		for(j = 0 ; j < time ; j ++);

	}



}

void EXTII9_callback(void)
{


	// EXTI_flag = 1;
	LCD_WRITE_STRING("IRQ EXTI9 happened _|-");
	mywait(400);
    LCD_clear_screen();


}

void RCC_clock_init(void){

	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	AFIO_GPIOE_CLK_EN();


}




int main(void)
{

//RCC init
RCC_clock_init();

//ECU Init
LCD_INIT();
mywait(200);


//set an interrupt

PINCONFIG.EXTI_PIN =  EXTI9PB9;
PINCONFIG.Trigger_Case = EXTI_Trigger_RSISING;
PINCONFIG.P_IRQ_CallBack = EXTII9_callback;
PINCONFIG.IRQ_EN = EXTI_IRQ_Enalbe;
//MCAL_EXTI_GPIO_Init(&EXTI_PinConfig_t);

LCD_WRITE_STRING("LEARN IN DEPTH");
mywait(200);
LCD_clear_screen();

//Code
EXTI_flag = 1;
while(1){



}



	return 0;
}
